Repository lightly-ai/lightly, pull requests merged in 2024-10, with the labels that each got.

#1652 Adding type check for serve.py
  lightly/api/serve.py
  pyproject.toml
Labels: enhancement

#1662 Addition of RFFT2D and IRFFT2D transforms
  lightly/transforms/__init__.py
  lightly/transforms/irfft2d_transform.py
  lightly/transforms/rfft2d_transform.py
  tests/transforms/test_irfft2d_transform.py
  tests/transforms/test_rfft2d_transform.py
Labels: feature, hacktoberfest-accepted

#1681 Lambda functions removed from examples
  examples/notebooks/pytorch/aim.ipynb
  examples/notebooks/pytorch/dino.ipynb
  examples/notebooks/pytorch/ijepa.ipynb
  examples/notebooks/pytorch/mae.ipynb
  examples/notebooks/pytorch/msn.ipynb
  examples/notebooks/pytorch/pmsn.ipynb
  examples/notebooks/pytorch/simmim.ipynb
  examples/notebooks/pytorch/swav.ipynb
  examples/notebooks/pytorch/swav_queue.ipynb
  examples/notebooks/pytorch/vicregl.ipynb
  examples/notebooks/pytorch_lightning/aim.ipynb
  examples/notebooks/pytorch_lightning/dino.ipynb
  examples/notebooks/pytorch_lightning/mae.ipynb
  examples/notebooks/pytorch_lightning/msn.ipynb
  examples/notebooks/pytorch_lightning/pmsn.ipynb
  examples/notebooks/pytorch_lightning/simmim.ipynb
  examples/notebooks/pytorch_lightning/swav.ipynb
  examples/notebooks/pytorch_lightning/swav_queue.ipynb
  examples/notebooks/pytorch_lightning/vicregl.ipynb
  examples/notebooks/pytorch_lightning_distributed/aim.ipynb
  examples/notebooks/pytorch_lightning_distributed/dino.ipynb
  examples/notebooks/pytorch_lightning_distributed/mae.ipynb
  examples/notebooks/pytorch_lightning_distributed/msn.ipynb
  examples/notebooks/pytorch_lightning_distributed/pmsn.ipynb
  examples/notebooks/pytorch_lightning_distributed/simmim.ipynb
  examples/notebooks/pytorch_lightning_distributed/swav.ipynb
  examples/notebooks/pytorch_lightning_distributed/vicregl.ipynb
  examples/pytorch/aim.py
  examples/pytorch/dino.py
  examples/pytorch/ijepa.py
  examples/pytorch/mae.py
  examples/pytorch/msn.py
  examples/pytorch/pmsn.py
  examples/pytorch/simmim.py
  examples/pytorch/swav.py
  examples/pytorch/swav_queue.py
  examples/pytorch/vicregl.py
  examples/pytorch_lightning/aim.py
  examples/pytorch_lightning/dino.py
  examples/pytorch_lightning/mae.py
  examples/pytorch_lightning/msn.py
  examples/pytorch_lightning/pmsn.py
  examples/pytorch_lightning/simmim.py
  examples/pytorch_lightning/swav.py
  examples/pytorch_lightning/swav_queue.py
  examples/pytorch_lightning/vicregl.py
  examples/pytorch_lightning_distributed/aim.py
  examples/pytorch_lightning_distributed/dino.py
  examples/pytorch_lightning_distributed/mae.py
  examples/pytorch_lightning_distributed/msn.py
  examples/pytorch_lightning_distributed/pmsn.py
  examples/pytorch_lightning_distributed/simmim.py
  examples/pytorch_lightning_distributed/swav.py
  examples/pytorch_lightning_distributed/vicregl.py
Labels: hacktoberfest-accepted

#1682 Updated docstring for lightly/embedding subpackage
  lightly/embedding/callbacks.py
  lightly/embedding/embedding.py
Labels: documentation

#1685 Move classes and public functions to top of files
  lightly/data/_image.py
  lightly/data/_video.py
  lightly/data/dataset.py
  lightly/loss/regularizer/co2.py
  lightly/loss/sym_neg_cos_sim_loss.py
  lightly/models/modules/heads.py
  lightly/models/modules/memory_bank.py
  lightly/utils/debug.py
  lightly/utils/hipify.py
Labels: enhancement

#1668 Add Documentation for lightly/models/utils.py
  lightly/models/utils.py
Labels: hacktoberfest-accepted

#1692 Implementation of GaussianMixtureMasksTransform
  lightly/transforms/__init__.py
  lightly/transforms/gaussian_mixture_masks_transform.py
  tests/transforms/test_gaussian_mixture_masks.py
Labels: feature, hacktoberfest-accepted

#1697 Add Documentation for lightly/loss subpackage.
  lightly/loss/barlow_twins_loss.py
  lightly/loss/dcl_loss.py
  lightly/loss/dino_loss.py
  lightly/loss/emp_ssl_loss.py
  lightly/loss/hypersphere_loss.py
  lightly/loss/ibot_loss.py
  lightly/loss/koleo_loss.py
  lightly/loss/mmcr_loss.py
  lightly/loss/msn_loss.py
  lightly/loss/negative_cosine_similarity.py
  lightly/loss/ntx_ent_loss.py
  lightly/loss/pmsn_loss.py
  lightly/loss/regularizer/__init__.py
  lightly/loss/regularizer/co2.py
  lightly/loss/swav_loss.py
  lightly/loss/sym_neg_cos_sim_loss.py
  lightly/loss/tico_loss.py
  lightly/loss/vicreg_loss.py
  lightly/loss/vicregl_loss.py
  lightly/loss/wmse_loss.py
Labels: hacktoberfest-accepted

#1694 Added the Amplitude Rescaling Transform
  lightly/transforms/__init__.py
  lightly/transforms/amplitude_rescale_transform.py
  tests/transforms/test_amplitude_rescale_transform.py
Labels: enhancement, hacktoberfest-accepted

#1707 Cleanup: _image.py and _utils.py file in data subpackage
  lightly/data/_image_loaders.py
  lightly/data/_utils.py
Labels: hacktoberfest-accepted
